package dev.docuconf.kotlin.core

/**
 * Writes a [Contract] as `contract.cue` (SPEC §4): plain data unified with `contract.#Contract`.
 * Output is deterministic: variables, file inputs and overlays are sorted by name, fields in a fixed order.
 */
public object CueWriter {
    public const val HEADER: String = "// Code generated by docuconf. DO NOT EDIT."

    private val identifier = Regex("^[A-Za-z][A-Za-z0-9_]*$")
    private val keywords = setOf("package", "import", "for", "in", "if", "let", "true", "false", "null", "func")

    /**
     * @param packageName the CUE package clause; defaults to the service name with `-` replaced by `_`.
     */
    public fun write(contract: Contract, packageName: String? = null): String {
        val w = Writer()
        w.line(HEADER)
        w.line("package ${packageName ?: defaultPackage(contract.service)}")
        w.line()
        w.line("import \"docuconf.dev/contract\"")
        w.line()
        w.open("contract.#Contract & {")
        w.field("apiVersion", str("docuconf.dev/v1alpha1"))
        w.field("kind", str("ConfigContract"))
        w.open("metadata: {")
        w.field("name", str(contract.service))
        contract.appVersion?.let { w.field("appVersion", str(it)) }
        val g = contract.generator
        w.field("generator", "{language: ${str(g.language)}, sdk: ${str(g.sdk)}, version: ${str(g.version)}}")
        w.close()
        w.open("vars: {")
        for (v in contract.vars.sortedBy { it.name }) writeVar(w, v)
        w.close()
        if (contract.files.isNotEmpty()) {
            w.open("files: {")
            for (f in contract.files.sortedBy { it.name }) writeFile(w, f)
            w.close()
        }
        if (contract.overlays.isNotEmpty()) {
            w.open("overlays: {")
            for (o in contract.overlays.sortedBy { it.name }) writeOverlay(w, o)
            w.close()
        }
        w.close()
        return w.toString()
    }

    /** A valid CUE package name for a service name. */
    public fun defaultPackage(service: String): String {
        val p = service.replace('-', '_')
        return if (p.firstOrNull()?.isLetter() == true) p else "svc_$p"
    }

    private fun writeVar(w: Writer, v: VarSpec) {
        w.open("${label(v.name)}: {")
        w.field("type", str(v.type.wire))
        w.field("description", str(v.description))
        v.details?.let { w.field("details", str(it)) }
        if (v.required) w.field("required", "true")
        if (v.secret) w.field("secret", "true")
        v.group?.let { w.field("group", str(it)) }
        v.configKey?.let { w.field("configKey", str(it)) }
        if (v.examples.isNotEmpty()) w.field("examples", list(v.examples.map(::str)))
        v.deprecated?.let { writeDeprecated(w, it) }
        if (v.type == VarType.DURATION) w.field("encoding", str(v.durationEncoding.wire))
        if (v.type == VarType.LIST) {
            w.field("items", str(v.items!!.wire))
            w.field("encoding", str(v.listEncoding.wire))
            if (v.listEncoding == ListEncoding.CSV && v.separator != ",") w.field("separator", str(v.separator))
        }
        v.values?.let { w.field("values", list(it.map(::str))) }
        v.schemes?.let { w.field("schemes", list(it.map(::str))) }
        v.min?.let { w.field("min", value(it, w.depth)) }
        v.max?.let { w.field("max", value(it, w.depth)) }
        v.minDuration?.let { w.field("min", str(it)) }
        v.maxDuration?.let { w.field("max", str(it)) }
        v.minLength?.let { w.field("minLength", it.toString()) }
        v.maxLength?.let { w.field("maxLength", it.toString()) }
        v.pattern?.let { w.field("pattern", str(it)) }
        v.minItems?.let { w.field("minItems", it.toString()) }
        v.maxItems?.let { w.field("maxItems", it.toString()) }
        v.itemMin?.let { w.field("itemMin", it.toString()) }
        v.itemMax?.let { w.field("itemMax", it.toString()) }
        v.itemMinLength?.let { w.field("itemMinLength", it.toString()) }
        v.itemMaxLength?.let { w.field("itemMaxLength", it.toString()) }
        v.schema?.let { w.field("schema", value(it, w.depth)) }
        v.default?.let { w.field("default", value(if (v.type == VarType.FLOAT && it is JsonValue.Int) JsonValue.Float(it.value.toDouble()) else it, w.depth)) }
        w.close()
    }

    private fun writeFile(w: Writer, f: FileSpec) {
        w.open("${label(f.name)}: {")
        w.field("type", str(f.type.wire))
        f.format?.let { w.field("format", str(it.wire)) }
        f.keystoreFormat?.let { w.field("format", str(it.wire)) }
        w.field("description", str(f.description))
        f.details?.let { w.field("details", str(it)) }
        if (f.required) w.field("required", "true")
        // tls and keystore are always secret; the meta-schema fixes the field for them.
        if (f.secret && f.type != FileType.TLS && f.type != FileType.KEYSTORE) w.field("secret", "true")
        f.group?.let { w.field("group", str(it)) }
        f.deprecated?.let { writeDeprecated(w, it) }
        w.field("path", str(f.path))
        f.pathEnv?.let { w.field("pathEnv", str(it)) }
        if (f.reload == Reload.WATCH) w.field("reload", str("watch"))
        f.maxSize?.let { w.field("maxSize", it.toString()) }
        f.dnsNames?.let { w.field("dnsNames", list(it.map(::str))) }
        f.keyAlgorithms?.let { w.field("keyAlgorithms", list(it.map { a -> str(a.wire) })) }
        f.minRemaining?.let { w.field("minRemaining", str(it)) }
        if (f.requireCA) w.field("requireCA", "true")
        f.minCertificates?.let { if (it != 1) w.field("minCertificates", it.toString()) }
        f.passwordVar?.let { w.field("passwordVar", str(it)) }
        f.pattern?.let { w.field("pattern", str(it)) }
        f.minLength?.let { w.field("minLength", it.toString()) }
        f.maxLength?.let { w.field("maxLength", it.toString()) }
        f.schema?.let { w.field("schema", value(it, w.depth)) }
        w.close()
    }

    private fun writeOverlay(w: Writer, o: OverlaySpec) {
        w.open("${label(o.name)}: {")
        o.description?.let { w.field("description", str(it)) }
        w.field("format", str(o.format.wire))
        w.field("path", str(o.path))
        w.field("keySeparator", str(o.keySeparator))
        w.field("reload", str(o.reload.wire))
        w.close()
    }

    private fun writeDeprecated(w: Writer, d: Deprecation) {
        val replaced = d.replacedBy?.let { ", replacedBy: ${str(it)}" } ?: ""
        w.field("deprecated", "{message: ${str(d.message)}$replaced}")
    }

    private fun str(s: String): String = buildString { quoteJson(s, this) }

    private fun list(items: List<String>): String = items.joinToString(", ", "[", "]")

    private fun label(name: String): String = if (identifier.matches(name) && name !in keywords) name else str(name)

    /** A JSON value as CUE. Objects and lists holding objects span lines, indented with tabs from [depth]. */
    private fun value(v: JsonValue, depth: Int): String = when (v) {
        JsonValue.Null -> "null"
        is JsonValue.Bool -> v.value.toString()
        is JsonValue.Int -> v.value.toString()
        is JsonValue.Float -> formatFloat(v.value)
        is JsonValue.Str -> str(v.value)
        is JsonValue.Arr -> if (v.items.none { it is JsonValue.Obj || it is JsonValue.Arr }) {
            list(v.items.map { value(it, depth) })
        } else {
            val inner = "\t".repeat(depth + 1)
            v.items.joinToString(",\n", "[\n", "\n" + "\t".repeat(depth) + "]") { inner + value(it, depth + 1) }
        }
        is JsonValue.Obj -> if (v.fields.isEmpty()) {
            "{}"
        } else {
            val inner = "\t".repeat(depth + 1)
            v.fields.entries.joinToString("\n", "{\n", "\n" + "\t".repeat(depth) + "}") { (k, x) -> "$inner${label(k)}: ${value(x, depth + 1)}" }
        }
    }

    private class Writer {
        private val sb = StringBuilder()
        var depth = 0
            private set

        fun line(text: String = "") {
            if (text.isNotEmpty()) repeat(depth) { sb.append('\t') }
            sb.append(text).append('\n')
        }

        fun open(header: String) {
            line(header)
            depth++
        }

        fun close() {
            depth--
            line("}")
        }

        fun field(name: String, value: String) = line("$name: $value")

        override fun toString() = sb.toString()
    }
}
