// Code generated by docuconf. DO NOT EDIT.
package app

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "app"
		generator: {language: "kotlin", sdk: "docuconf-hoplite", version: "0.1.0"}
	}
	vars: {
		DATABASE_URL: {
			type: "url"
			description: "Postgres connection URL"
			required: true
			secret: true
			configKey: "databaseUrl"
			schemes: ["postgres"]
		}
		LOG_LEVEL: {
			type: "enum"
			description: "Minimum log level"
			configKey: "logLevel"
			values: ["debug", "info", "warn"]
			default: "info"
		}
		PORT: {
			type: "int"
			description: "HTTP listen port"
			configKey: "port"
			min: 1
			max: 65535
			default: 8080
		}
		REQUEST_TIMEOUT: {
			type: "duration"
			description: "Upstream request timeout"
			configKey: "requestTimeout"
			encoding: "iso8601"
			max: "1m"
			default: "10s"
		}
	}
}
