package dev.docuconf.core

/** Generates Markdown documentation of a contract's inputs (SPEC §11.2, "SHOULD"). */
public object MarkdownWriter {
    public fun write(contract: Contract): String = buildString {
        append("# ${contract.service} configuration\n\n")
        append("Generated by docuconf from the service's declaration. Do not edit.\n\n")
        append("## Environment variables\n\n")
        append("| Name | Type | Required | Default | Description |\n|---|---|---|---|---|\n")
        for (v in contract.vars.sortedBy { it.name }) {
            val type = buildString {
                append(v.type.wire)
                if (v.type == VarType.LIST) append(" of ${v.items?.wire}")
                if (v.secret) append(", secret")
                constraints(v).takeIf { it.isNotEmpty() }?.let { append(" (").append(it).append(")") }
            }
            val default = v.default?.let { "`${cell(if (it is JsonValue.Str) it.value else it.toString())}`" } ?: ""
            val deprecated = v.deprecated?.let { " **Deprecated:** ${it.message}" } ?: ""
            append("| `${v.name}` | ${cell(type)} | ${if (v.required) "yes" else "no"} | $default | ${cell(v.description)}$deprecated |\n")
        }
        if (contract.files.isNotEmpty()) {
            append("\n## Files\n\n")
            append("| Name | Type | Path | Required | Description |\n|---|---|---|---|---|\n")
            for (f in contract.files.sortedBy { it.name }) {
                val path = "`${f.path}`" + (f.pathEnv?.let { " (or `$$it`)" } ?: "")
                val type = f.type.wire + (f.format?.let { " (${it.wire})" } ?: "") + (if (f.isSecret) ", secret" else "")
                append("| `${f.name}` | $type | $path | ${if (f.required) "yes" else "no"} | ${cell(f.description)} |\n")
            }
        }
    }

    private fun constraints(v: VarSpec): String = listOfNotNull(
        v.min?.let { "min ${it.show()}" },
        v.max?.let { "max ${it.show()}" },
        v.minDuration?.let { "min $it" },
        v.maxDuration?.let { "max $it" },
        v.minLength?.let { "minLength $it" },
        v.maxLength?.let { "maxLength $it" },
        v.pattern?.let { "pattern `$it`" },
        v.schemes?.let { "schemes ${it.joinToString("/")}" },
        v.values?.let { "one of ${it.joinToString(", ")}" },
        v.minItems?.let { "minItems $it" },
        v.maxItems?.let { "maxItems $it" },
    ).joinToString("; ")

    private fun cell(s: String): String = s.replace("|", "\\|").replace("\n", " ")
}
