// Code generated by docuconf. DO NOT EDIT.
package gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "gateway"
		generator: {language: "kotlin", sdk: "docuconf-hoplite", version: "0.1.0"}
	}
	vars: {
		ADMINPORTS: {
			type: "list"
			description: "Extra ports that serve the admin API"
			configKey: "adminPorts"
			items: "int"
			encoding: "csv"
			maxItems: 4
			default: []
		}
		BROKERS: {
			type: "list"
			description: "Kafka brokers to publish access logs to"
			examples: ["kafka-0:9092"]
			items: "string"
			encoding: "csv"
			minItems: 1
			default: ["kafka-0:9092", "kafka-1:9092"]
		}
		COMPRESS: {
			type: "bool"
			description: "Whether to gzip responses"
			default: true
		}
		DB_POOLSIZE: {
			type: "int"
			description: "Connection pool size"
			group: "database"
			configKey: "db.poolSize"
			min: 1
			max: 100
			default: 10
		}
		DB_URL: {
			type: "url"
			description: "Primary Postgres connection string"
			required: true
			secret: true
			group: "database"
			schemes: ["postgres", "postgresql"]
		}
		IDLE: {
			type: "duration"
			description: "How long idle upstream connections are kept"
			encoding: "iso8601"
			default: "1m30s"
		}
		LEGACYPORT: {
			type: "int"
			description: "Old name of the listen port"
			configKey: "legacyPort"
			deprecated: {message: "Use PORT.", replacedBy: "PORT"}
			min: -2147483648
			max: 2147483647
		}
		LOGLEVEL: {
			type: "enum"
			description: "Minimum log level emitted"
			configKey: "logLevel"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		PARTNER_PASSWORD: {
			type: "string"
			description: "Password for the partner mTLS keystore"
			secret: true
		}
		POD_NAMESPACE: {
			type: "string"
			description: "Namespace the gateway runs in, for metrics labels"
			required: true
			group: "runtime"
		}
		PORT: {
			type: "int"
			description: "HTTP listen port"
			min: 1
			max: 65535
			default: 8080
		}
		PUBLICURL: {
			type: "url"
			description: "Public base URL of the gateway"
			required: true
			configKey: "publicUrl"
			schemes: ["https"]
		}
		RATELIMITS: {
			type: "json"
			description: "Default per-client rate limits"
			configKey: "rateLimits"
			schema: {
				type: "object"
				required: ["perMinute"]
				additionalProperties: false
				properties: {
					perMinute: {
						description: "Requests per minute per client"
						type: "integer"
						minimum: 1
						maximum: 2147483647
					}
					burst: {
						description: "Extra requests allowed in a burst"
						type: "integer"
						minimum: 0
						maximum: 2147483647
					}
				}
			}
		}
		REGION: {
			type: "string"
			description: "Cloud region code"
			group: "cloud"
			maxLength: 20
			pattern: "^[a-z]{2}-[a-z]+-[0-9]$"
			default: "eu-west-1"
		}
		TIER: {
			type: "enum"
			description: "Billing tier of this deployment"
			values: ["free", "pro"]
			default: "free"
		}
		TIMEOUT: {
			type: "duration"
			description: "Upstream request timeout"
			encoding: "iso8601"
			min: "1s"
			max: "5m"
			default: "30s"
		}
		TRACERATIO: {
			type: "float"
			description: "Fraction of requests to trace"
			configKey: "traceRatio"
			min: 0.0
			max: 1.0
			default: 0.1
		}
	}
	files: {
		geoip: {
			type: "binary"
			description: "GeoIP database for country-based routing"
			path: "/data/geoip/GeoLite2-City.mmdb"
			maxSize: 134217728
		}
		license: {
			type: "text"
			description: "Gateway licence key"
			required: true
			secret: true
			path: "/etc/gateway/license/license.key"
			pattern: "^[A-Z0-9]{5}(-[A-Z0-9]{5}){3}\\n?$"
		}
		"partner-keystore": {
			type: "keystore"
			format: "pkcs12"
			description: "Client certificate for mTLS to the partner API"
			path: "/etc/gateway/partner/keystore.p12"
			passwordVar: "PARTNER_PASSWORD"
		}
		routes: {
			type: "config"
			format: "yaml"
			description: "Routing table: path prefixes and their upstreams"
			required: true
			path: "/etc/gateway/routes/routes.yaml"
			pathEnv: "ROUTES_FILE"
			maxSize: 65536
			schema: {
				type: "object"
				required: ["routes"]
				additionalProperties: false
				properties: {
					routes: {
						type: "array"
						items: {
							type: "object"
							required: ["match", "upstream"]
							additionalProperties: false
							properties: {
								match: {
									type: "string"
									pattern: "^/"
								}
								upstream: {
									type: "string"
									pattern: "^https?://"
								}
								timeout: {
									type: "string"
								}
							}
						}
						minItems: 1
					}
				}
			}
		}
		"serving-tls": {
			type: "tls"
			description: "Certificate the gateway serves HTTPS with"
			required: true
			path: "/etc/gateway/tls"
			dnsNames: ["gateway.internal", "api.example.com"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
		}
		"upstream-ca": {
			type: "caBundle"
			description: "Private CAs the gateway trusts for upstream TLS"
			path: "/etc/gateway/ca/bundle.pem"
			pathEnv: "SSL_CERT_FILE"
		}
	}
}
